apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-prom
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: http-grafana
  selector:
    app: grafana
