apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring-prom
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      cloud.google.com/load-balancer-type: Internal

spec:
  type: LoadBalancer
  selector: 
    app: prometheus-server
  ports:
    - port: 9090
      targetPort: 9090 
